name: CI
on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: ['*']

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      # with:
      #   submodules: true
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo
    - name: run tests
      run: |
        cargo -Vv
        rustc -Vv
        git submodule update --init
        (cd curl-sys/curl && git checkout 92179353e5cac4cfb294a1fdcbdbf5d682fc40a1)
        cargo t --features http2 --test eric
        (cd curl-sys/curl && git checkout 8beff4355956e3d18ceb3afc21c1f3edec82543c)
        cargo t --features http2 --test eric
        (cd curl-sys/curl && git checkout ebe3fdb0e36b6fe8929e5fc90bbaf4e97f9cb962)
        cargo t --features http2 --test eric
